### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by cocowalla** [dazinator/DotNet.Glob#18]
The current 1-line [license file](https://github.com/dazinator/DotNet.Glob/blob/develop/LICENSE) is just a tad ambiguous :)

It would be good if you could [choose](https://choosealicense.com) a more explicit license.

**Comment by dazinator** [comment]
+1 - I'll get on it

**Comment by cocowalla** [comment]
Gentle reminder ;)

**Comment by dazinator** [comment]
Sorry, i keep meaning to add an MIT licence but never get to it.

**Comment by cocowalla** [comment]
Good choice 👍
