### ISSUE TITLE
Does not recognise : or _ as valid characters

### ISSUE THREAD

**Issue by PeAb** [dazinator/DotNet.Glob#20]
On Windows, C:\THIS_IS_A_DIR\somefile doesn't match with the glob C:\THIS_IS_A_DIR\\*

**Comment by dazinator** [comment]
Thank you - I'll add a test case for that and take a look!

**Comment by dazinator** [comment]
This is fixed in the latest development build. NuGet package for that is here: https://www.nuget.org/packages/DotNet.Glob/1.5.0-unstable0013

**Comment by PeAb** [comment]
Works for me now, thanks!
