### ISSUE TITLE
"C:\THIS_IS_A_DIR\**\somefile.txt" matches wrongly to "C:\THIS_IS_A_DIR\awesomefile.txt"

### ISSUE THREAD

**Issue by thomas-patzig** [dazinator/DotNet.Glob#27]
see the test "DotNet.Glob.Tests.GlobTests.Does_Not_Match"
should not match but does it

```
[Theory]
[InlineData( "C:\\THIS_IS_A_DIR\\**\\somefile.txt", "C:\\THIS_IS_A_DIR\\awesomefile.txt" )]
public void Does_Not_Match(string pattern, params string[] testStrings)
{
    var glob = Globbing.Glob.Parse(pattern);
    foreach (var testString in testStrings)
    {
        Assert.False(glob.IsMatch(testString));
    }
}

```

**Comment by dazinator** [comment]
Ah yes, thank you for finding this bug with the behavior of `**`. I'll get it fixed and leave those tests in as regression tests for the future.

**Comment by dazinator** [comment]
This has been fixed in the latest stable re;ease, nuget package version 1.6.1.

**Comment by czjlorenz** [comment]
thank you very much for the quick fix

**Comment by dazinator** [comment]
You are welcome!
