### ISSUE TITLE
wrong match for "C:\name.ext" to glob pattern "C:\name\**"

### ISSUE THREAD

**Issue by czjlorenz** [dazinator/DotNet.Glob#29]
given the following test code ...

`var glob = DotNet.Globbing.Glob.Parse( @"C:\name\**" );`
`bool result = glob.IsMatch( @"C:\name.ext" );`
`result = glob.IsMatch( @"C:\name_longer.ext" `);`

... the result of IsMatch() is true in both cases. To my mind this is wrong. The result should be false. I am using DotNet.Glob-1.6.1 from nuget.org.

**Comment by dazinator** [comment]
Thanks for finding this. I'll add test coverage for this case and get back to you!

**Comment by dazinator** [comment]
Verified.

**Comment by dazinator** [comment]
Hotfix pushed. Once appveyor builds and publishes (takes a few minutes) version 1.6.2 will appear on nuget - upgrade to that for the fix.

**Comment by dazinator** [comment]
- FYI, it turned out to be 1.6.3 in the end - I had a build error in my cake script that needed to also be addressed.

**Comment by czjlorenz** [comment]
Thanks for the super fast fix. Unfortunately I cannot use it. The new assembly does not have a strong, while 1.6.1 had. Upon closer inspection only half of the 1.6.3 DLLs have a strong name. For 1.6.1 the other half has a strong name. I think either all of the compiled DLLs have a strong name or none. Also the DLLs all have the assembly version 1.0.0.0. Matching the nuget version would be best practice AFAIK.

Should I create two separate issues?
