### ISSUE TITLE
match assembly version and nuget version

### ISSUE THREAD

**Issue by czjlorenz** [dazinator/DotNet.Glob#30]
I noticed that all of the DLLs in the nuget have the version 1.0.0.0 in their Win32 version resources and the .NET assembly names. It would be nice if this would be the same as the nuget version.

**Comment by dazinator** [comment]
Yeah, at the moment I am waiting on gitversion msbuild task to work under dotnet cli: https://github.com/GitTools/GitVersion/issues/1175

Once that's done I'll get the assembly versions stamped again.

**Comment by dazinator** [comment]
https://github.com/CometaSolutions/UtilPack/issues/20

**Comment by dazinator** [comment]
Hmm seems I spoke prematurely.
