### ISSUE TITLE
Pattern **/ not working

### ISSUE THREAD

**Issue by renzoyzz** [dazinator/DotNet.Glob#34]
The pattern "\*\*/app*.js" for example should match when a path looks like dist/app.js or dist/app.a72ka8234.js. The issue is it is not evaluating the "\*\*/" part of the glob pattern as the documentation only mentions "/\*\*/" as a valid pattern. Any plan to implement this soon?

**Comment by dazinator** [comment]
Interesting. Yes I will look into this and get back to you.

**Comment by renzoyzz** [comment]
@dazinator thanks!

**Comment by dazinator** [comment]
Fixed in version 1.6.6, and regression test added. Should appear on nuget soon! Thanks for reporting.
