### ISSUE TITLE
add target framework "net47"

### ISSUE THREAD

**Issue by thomas-patzig** [dazinator/DotNet.Glob#36]
`<TargetFrameworks>netstandard1.1;net45;net46;net47;net4</TargetFrameworks>`

**Comment by dazinator** [comment]
I can do this, and I do have targets for net4, 45 and 46 - but to be honest, I am not sure what the benefits are.  I believe net47 should be able to run assemblies compiled for net46, net45 (not sure about net4) as well as all netstandard versions upto 1.6. This means the existing compilation targets should already be enough for net47 support. I'd rather look at removing any unnecessary compalition targets over adding more!
