### ISSUE TITLE
endless loop in version 1.6.6

### ISSUE THREAD

**Issue by thomas-patzig** [dazinator/DotNet.Glob#37]
try this code:
localPattern="C:\sources\COMPILE\**\MSVC*120.DLL"
localInput="C:\sources\COMPILE\ANTLR3.RUNTIME.DLL"

`			var glob = Glob.Parse( localPattern );
			return glob.IsMatch( localInput );
`

endless loop in "WildcardDirectoryTokenEvaluator.IsMatch":

currentPosition=51
maxPos=51
isMatch=false

`                // Match until maxpos, is reached.
                while (currentPosition <= maxPos)
                {
                    // Test at current position.
                    isMatch = _subEvaluator.IsMatch(allChars, currentPosition, out newPosition);
                    if (isMatch)
                    {
                        return isMatch;
                    }

                    // Iterate until we hit a seperator or maxPos.
                    while (currentPosition < maxPos)
                    {
                        currentPosition = currentPosition + 1;
                        currentChar = allChars[currentPosition];
                        if (currentChar == '/' || currentChar == '\\')
                        {
                            // advance past the seperator.
                            currentPosition = currentPosition + 1;
                            break;
                        }
                    }
                }
`

**Comment by dazinator** [comment]
Ouch.. nasty! It seems I introduced this as a result of my last fix! I'll add a test case and fix this as soon as I can! 
Thanks

**Comment by dazinator** [comment]
Hmm I can't replicate this. In jy unit test IsMatch correctly returns false..

**Comment by dazinator** [comment]
an you provide a repro?

**Comment by dazinator** [comment]
I am closing this as I can't repro.

I created new console application and installed 1.6.6.

I then did this:

```
class Program
    {
        static void Main(string[] args)
        {
            string localPattern = @"C:\sources\COMPILE*\MSVC120.DLL";
            string localInput = @"C:\sources\COMPILE\ANTLR3.RUNTIME.DLL";

            bool isMAtch = DotNet.Globbing.Glob.Parse(localPattern).IsMatch(localInput);
            Console.WriteLine("IsMatch: " + isMAtch);
        }
    }
```

The output was:

![image](https://user-images.githubusercontent.com/3176632/30773195-956677a4-a063-11e7-82bb-f17d2a500c78.png)

**Comment by thomas-patzig** [comment]
try this code:

`
  var x = Glob.Parse( @"C:\sources\x-y 1\BIN\DEBUG\COMPILE\**\MSVC*120.DLL" );
  x.IsMatch( @"C:\sources\x-y 1\BIN\DEBUG\COMPILE\ANTLR3.RUNTIME.DLL" );
`

I think it's the blank space in path "x-y 1"

**Comment by thomas-patzig** [comment]
Hi dazinator,

do you reopen this issue or should I create a new one?

**Comment by dazinator** [comment]
Have reopened. I will investigate with the new test case you have provided, hopefully will catch the problem this time, thank you.

**Comment by dazinator** [comment]
Good news - I have replicated this using your last example - thank you. I will release an updated patch version to nuget.org momentarily.

**Comment by dazinator** [comment]
Fixed as of 1.6.9: https://www.nuget.org/packages/DotNet.Glob/1.6.9

**Comment by thomas-patzig** [comment]
it works
thanks

**Comment by dazinator** [comment]
No problem. Thank you for reporting.
