### ISSUE TITLE
Glob.Match InvalidOperationException

### ISSUE THREAD

**Issue by PazerOP** [dazinator/DotNet.Glob#39]
Calling `Glob.Match()` on certain globs/input strings will produce an `InvalidOperationException` with the message "Index was outside the bounds of the array". Repro for v1.6.9:

```C#
Glob.Parse("*://*wikia.com/**").Match("chrome://extensions");
```

**Comment by dazinator** [comment]
What version are you using?

**Comment by PazerOP** [comment]
Latest, 1.6.9.

**Comment by dazinator** [comment]
That's odd. Are you sure you are calling `Match` and not `IsMatch()` ?
There used to be a `Match` method but I removed it recently: https://github.com/dazinator/DotNet.Glob/blob/develop/src/DotNet.Glob/Glob.cs#L40

**Comment by dazinator** [comment]
Ah I see. I removed it as of the latest pre-release (alpha) package. But it is there in the last stable release 1.6.9 as you have seen. Can you use `IsMatch()` instead?

**Comment by dazinator** [comment]
For background: https://github.com/dazinator/DotNet.Glob/issues/28
