### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by cocowalla** [dazinator/DotNet.Glob#40]
I'm using the latest Nuget package, 1.7.0-unstable0022, and one of my tests found an issue whereby the call to `IsMatch` never returns (I assume due to an infinite loop).

Pattern: `C:\Test\**\*.txt`
Test String: `C:\Test\file.dat`

This issue was not present in 1.7.0-unstable0018

**Comment by dazinator** [comment]
Apologies, this was fixed as of the last stable release (1.6.9) and a newer pre-release package should have also been published with the fix, but for some reason the pre-release nugget package was never published. Suggestion for now would be to take the latest stable release - version 1.6.9. Let me know if you still have any  problems.

**Comment by cocowalla** [comment]
Ah, OK, Nuget only shows 10 or so versions by default, so I didn't see 1.6.9 was newer than the 1.7 unstable versions.

**Comment by dazinator** [comment]
No problem. Not sure why I newer pre-release package wasn't published but I will look into the appveyor build process to fix that for the future.
