### ISSUE TITLE
Case sensitivity option

### ISSUE THREAD

**Issue by bernhof** [dazinator/DotNet.Glob#41]
I like the project, works well so far for me. However, am missing an option to make glob case insensitive to mimic how Windows treats paths. Currently I have to make both glob pattern and file names lower case to achieve this. Seems like this could easily be baked in.

Keep up the good work!

**Comment by dazinator** [comment]
Good idea, I will look to add this to [GlobParseOptions](https://github.com/dazinator/DotNet.Glob/blob/develop/src/DotNet.Glob/GlobParseOptions.cs)

PR's for this are welcomed.
