### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by alphaleonis** [dazinator/DotNet.Glob#42]
The following lines generate an IndexOutOfRangeException:

````
var glob = Glob.Parse("C:\\Bin\\*.pdb");
glob.Match("C:\\Bin\\.vs");
````

**Comment by dazinator** [comment]
Thank you, I will add a test and assuming it replicates, I will roll out a fix in short order.

**Comment by dazinator** [comment]
@alphaleonis  I was not able to replicate this on latest develop branch. What version of dotnet glob nuget package are you using?

**Comment by dazinator** [comment]
@alphaleonis - As I can't replicate this, I will close this for now, but please re-open if you still have issues and can give me the version you are using!

**Comment by alphaleonis** [comment]
I was using the latest version from NuGet, i.e. 1.6.9. With that I can replicate it just by creating a new C# .NET Framework Console app, adding a package reference to DotNet.Glob, and adding the two lines in the bug to the main method. Running the program the causes an IndexOutOfRange exception. Perhaps it has already been fixed in the repo?

**Comment by dazinator** [comment]
Hmm not sure. But I added a test case for the above, and it passed. If you can manage to provide a failing test case, I will re-open and investigate. If not then I am a bit stumped.

**Comment by alphaleonis** [comment]
Well, it will be hard to reproduce now since the method appears to have been removed in a77ae3bb50791a4a4a3fd8745e35f37fd4222bda
;)

**Comment by dazinator** [comment]
Ah yes I see the confusion now apologies. `Match` was removed as per #28 - `IsMatch` should be used in the majority of cases.  My tests were done using IsMatch hence why I couldnt replicate! Match was indeed buggy as you discovered :-)
