### ISSUE TITLE
The nuget package have no strong name

### ISSUE THREAD

**Issue by edwardmeng** [dazinator/DotNet.Glob#45]
I'm getting error:
System.IO.FileLoadException: 'Could not load file or assembly 'DotNet.Glob, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required.
How I can use your package now? Or when will you fix it?

**Comment by edwardmeng** [comment]
I have copied the source code instead of package reference until the nuget package strongly-named.

**Comment by dazinator** [comment]
Fixed as of 2.0.3 which will appear on nuget shortly (if not already). Thanks for reporting.

**Comment by dazinator** [comment]
and FYI, If you wanted to continue to build from source, as of the latest commit, Debug builds should work as normal and produce a non-signed assembly.. However `Release` builds now expect to find a `DotNet.Glob.snk` key file in the repo root directory which it will use to sign the assemblies. This is not checked in, so you would have to create your own key file or disable assembly signing in that case.
