### ISSUE TITLE
Glob object model support for **

### ISSUE THREAD

**Issue by geekstew** [dazinator/DotNet.Glob#54]
Your globbing library is pretty nice. I was wondering if there’s a way to glob a pattern like this using the GlobBuilder: [a-zA-Z0-9]**

I can do it with string parsing, Glob.Parse(); but I seek high performance and was wondering if it would be possible to use the GlobBuilder to achieve the same. 
new GlobBuilder().LetterInRange('a', 'z').Wildcard().WildCard() -> [a-z]**

.Wildcard().WildCard() doesn't seem to be equivalent to "**". 

Also, another thing that’s problematic is being able to do, [a-zA-Z0-9]**. 

Finally, I want to glob files with a certain extension for e.g., *.pdb this doesn't seem to work at the moment?

**Comment by dazinator** [comment]
Thanks,
For `.Wildcard().WildCard() ` I think you want ` .DirectoryWildcard()`

For `[a-zA-Z0-9]**` are you saying you want to match any one character that is within the range a-z or A-Z or 0-9?

`**` can only be used when its the only thing in a segment.. i.e `foo/**/bar` is fine. `foo**` is not fine. 
At the moment I know you can create three seperate globs individually like so:

`[a-z]/**`, `[A-Z]/**` and `[0-9]/**`

However I am not sure (I have no test cases for this) you can create a single glob, that matches `a-zA-Z0-9`.

Hopefully I am making sense. You could try creating 3 glob instances as above, and then matching them in turn perhaps?

**Comment by dazinator** [comment]
To glob files with a certain extension?

`*.pdb` should work for example.

if you want any directory: `/**/*.pdb`

You can have a look at the test cases as they might help aid you.

**Comment by DoCode** [comment]
How to select multiple wildcards:  
`**/package.id/**/*.pdb`

**Comment by dazinator** [comment]
Closing this for now, hopefully your question is answered but let me know if not.

**Comment by geekstew** [comment]
@dazinator : Thanks for the detailed responses. I wasn't aware of the .DirectoryWildcard() for some reason. :)
