### ISSUE TITLE
[Question] Multiple directory wildcards

### ISSUE THREAD

**Issue by DoCode** [dazinator/DotNet.Glob#56]
How can I select multiple wildcard, directory levels?  
E.g.:
```
**/package.id/**/*.pdb
```

**Comment by dazinator** [comment]
That should work.. 
What are you having difficulty matching with that?

**Comment by dazinator** [comment]
You have gone silent :-)
I will close this for now but please comment if this is still unresolved for you.

**Comment by DoCode** [comment]
@dazinator thanks for that. I can confirm that it's working with the current/latest release.
