### ISSUE TITLE
What characters does the default setting allow in a file/folder path/name?

### ISSUE THREAD

**Issue by geekstew** [dazinator/DotNet.Glob#60]
On Windows, special file characters: \, /, :, *, ?, ", |, &lt;, &gt; are not allowed for file / folder names.
On *NIX/MAC, special file characters: \0, / are not allowed.

I hope the library honours this? :)

**Comment by dazinator** [comment]
You can see https://github.com/dazinator/DotNet.Glob/issues/52 for some history on this.
by `honour ` I think you mean that it shouldn't allow you to construct glob patterns that have characters that are invalid for the file system of the platform you are working on? Is that right? If so - itt used to have this as a setting that meant that it would try to prevent you from using invalid file path characters in glob patterns. The problem with this setting is that the "allowable" file path characters differs a lot from platform to platform and was very confusing. Also, globbing on file system paths is not the only one, for example I have seen people using this library to glob against windows registry entries, or url's etc so this setting wasn't valuable in those cases. Technically I don't see much value in dotnet glob making an assumptions about the underlying input string - i.e assuming it will always be a file system path is unnecessary coupling in my opinion. The only case I can think of where this might be a problem is where you allow users to input their own glob pattern, and construct a glob from it without doing any sanitisation to check for invalid file system characters. Is this the use case you have in mind?

**Comment by dazinator** [comment]
Closing this for now. If this is causing you some sort of exception or problem please feel free to comment further and i'll reopen if necessary.

**Comment by geekstew** [comment]
Thanks for the detailed explanation. On top of what you mention, there could be instances where windows is running on mac etc. In such cases the semantics become even more murkier. I agree with you. Thanks again.
