### ISSUE TITLE
Multiple Glob Patterns

### ISSUE THREAD

**Issue by majora2007** [dazinator/DotNet.Glob#90]
I'm trying to implement the ability to filter out files and folders during a scan. The idea is that while scanning, I may come across a special file that has patterns for what to Exclude from the search (from that point onward). 

Originally I sought to try this with built-in globbing library, but it is very inconsistent and cannot support "**/*.*" matching with "/root/file.ext", which is pretty critical for linux systems. This library does in fact support this.

However, it seems the only way for me to support multiple patterns is to generate a list of Glob Patterns and apply them on each file. Is there an API I'm missing?

**Comment by dazinator** [comment]
@majora2007 
Yeah creating a list and applying them to each file is the correct way. There is no sugar api for this provided by this library. Basically this library let's you parse a single pattern into glob object, and then use that pattern to match against strings. So if you want to deal with multiple patterns, you need to create a list like you said. I have actually created my own api's for this somewhere - I can't find it right now (another project) - where I created a wrapper - that has two inner lists of globs - the first is the list of patterns that should match, the second is the list of patterns that it must not match. A bit like an "include" and an "exclude" list. The wrapper allows you add patterns to these to lists, then exposes an IsMatch(testString) method - which has the logic around - if any of the include patterns match, return true, unless an exclude pattern also matches then etc. You can make something like this, but given use cases vary a lot and implementations are quite simple, I've not tried to provide something out of the box just yet.

**Comment by majora2007** [comment]
Thanks for the reply and direction, it looks like that might be the best approach as well for me. I just wanted to validate before I wrote code only to find out there was a simple way provided. Appreciate the quick reply.
